LANGUAGES = {
    "TR": {
        "Kompleks Kondenzasyon Polimeri": "Kompleks Kondenzasyon Polimeri",
        "Özel Sentez (AI Analizi Önerilir)": "Özel Sentez (AI Analizi Önerilir)",
        "Fonksiyonel Grup A": "Fonksiyonel Grup A",
        "Fonksiyonel Grup B": "Fonksiyonel Grup B",
        "Uç grupların reaksiyonu": "Uç grupların reaksiyonu",
        "Vinil Polimerizasyonu (Katılma)": "Vinil Polimerizasyonu (Katılma)",
        "Radikalik": "Radikalik",
        "Çift bağ açılması": "Çift bağ açılması",
        "Asit + Amin -> Amid + Su": "Asit + Amin -> Amid + Su",
        "Polyester Sentezi": "Polyester Sentezi",
        "Kademeli Polimerizasyon": "Kademeli Polimerizasyon",
        "Dikarboksilik Asit": "Dikarboksilik Asit",
        "Diol": "Diol",
        "Asit + Alkol -> Ester + Su": "Asit + Alkol -> Ester + Su",
        "Poliamid (Nylon) Sentezi": "Poliamid (Nylon) Sentezi",
        "Polikondenzasyon": "Polikondenzasyon", 
        "İzosiyanat + Alkol -> Üretan Bağı": "İzosiyanat + Alkol -> Üretan Bağı",
        "Diizosiyanat (Örn: TDI, MDI)": "Diizosiyanat (Örn: TDI, MDI)",
        "Diol / Polyol": "Diol / Polyol",
        "Poliladisyon": "Poliladisyon",
        "Poliüretan (PU) Sentezi": "Poliüretan (PU) Sentezi",
        "İzosiyanat + Amin -> Üre Bağı (Yan ürün yok)": "İzosiyanat + Amin -> Üre Bağı (Yan ürün yok)",
        "Diamin (Diamine)": "Diamin (Diamine)",
        "Diizosiyanat (Diisocyanate)": "Diizosiyanat (Diisocyanate)",
        "Basamaklı Polimerizasyon (Hızlı)": "Basamaklı Polimerizasyon (Hızlı)",
        "Poliüre (Polyurea) Sentezi": "Poliüre (Polyurea) Sentezi",
        "Dianhidrit + Diamin -> Poliimid": "Dianhidrit + Diamin -> Poliimid",
        "Dianhidrit": "Dianhidrit",
        "Diamin": "Diamin",
        "Siklo-dehidrasyon": "Siklo-dehidrasyon",
        "Poliimid Sentezi": "Poliimid Sentezi",
        "Generation": "Jenerasyon",
        "Çeşitlilik" : "Çeşitlilik",
        "Uretilen Polimer": "Üretilen Polimer",
        "Hedeflenen": "Hedeflenen",
        "yeşil_score": "Yeşil Skor",
        "predicted_monomers_image_caption": "Modelin Önerdiği Yapı Taşları",
        "msg_predicting": "Monomerler Tahmin Ediliyor",
        "msg_success":"Monomer Tahmini Başarılı!",
        "retro_structural": "1. Yapısal Ayrıştırma",
        "retro_t5_pred": "2. T5-Model Tahmini",
        "btn_predict_monomer": "Monomerleri Tahmin Et",
        "retro_t5_desc": "Eğittiğimiz model, moleküler yapıyı analiz ederek monomerleri tahmin ediyor.",
        "retro_auto_failed": "Otomatik analiz yapılamadı. Lütfen önerilen monomerleri manuel olarak inceleyin.",
        "kayitli_degil": "Ticari kayit yok",
        "control": "Kontrol",
        "commercial_check": "#### Ticari Bulunabilirlik (PubChem)",
        "baslangic_monomerleri":"**Olası Başlangıç Monomerleri:**",
        "yontem": "Yöntem",
        "mechanism": "Mekanizma",
        "retro_analysis_header": "Retrosentez Analizi",
        "retro_auto_failed": "Otomatik analiz yapılamadı. Lütfen önerilen monomerleri manuel olarak inceleyin.",
        "retro_rule_method": "Kural tabanlı omurga ayrıştırması ile bulunan gerçek monomer yapıları (T5 modeline bağlı değildir).",
        "retro_tentative": "Ayrıştırma yapıldı ancak doğrulama testini (fonksiyonel grup / atom korunumu) geçemedi — monomerler yaklaşık/eksik olabilir.",
        "retro_named_only": "Bu polimerin bilinen bir polimerleşme bağı yok; yalnızca olası mekanizma tahmini gösteriliyor, kesin monomer yapısı çıkarılamadı.",
        "get_free_api": "Ücretsiz API Key Almak İçin Tıkla(https://aistudio.google.com/app/apikey)",
        "chatbot_no_api": "Bu polimer hakkında detaylı kimyasal yorum almak için sol menüden **Google Gemini API Key** girmelisiniz.",
        "chatbot_desc": "PPolimer yapısı ve tahmin edilen özellikler hakkında detaylı kimyasal yorum almak için AI destekli ChatBot'u kullanın.",
        "download":"İndir",
        "report_ready": "Rapor hazır!",
        "report_getting_ready": "Rapor derleniyor... Lütfen bekleyin.",
        "pdf_report_info": "Bu rapor; tüm tahminleri, molekül yapısını, AI yorumlarını ve varsa sentez planını içerir.",
        "pdf_report": "PDF Raporu",
        "how_to_read": """                **Bu Grafikler Nasıl Okunur?**
                * **Yakınsama (Üst):** Yeşil çizgi sürekli düşmeli ve bir noktada yataylaşmalıdır (Plateau). Mavi çizgi yeşile çok yaklaşırsa popülasyon "öğrenmiş" demektir.
                * **Çeşitlilik (Alt):** Kırmızı çizginin sıfıra çok hızlı düşmemesi gerekir. Sıfıra düşerse model "Erken Yakınsama (Premature Convergence)" tuzağına düşmüştür; yani arama uzayını yeterince taramadan bir sonuca saplanmıştır.""",
        "genetic_algorithm_report": "Genetik Algoritma Performans Raporu",
        "novelty_explanation": "*Benzerlik, Tanimoto İndeksi (Morgan Fingerprints) kullanılarak hesaplanmıştır.*",
        "closest_sim": "En yakın benzerlik",
        "novel":"**KEŞİF:** Bu yapı eğitim setinde yok. Özgün bir tasarım.",
        "benzer_yapi": "Benzer Yapıyı Gör",
        "turev": "",
        "benzer":"",
        "copy":"",
        "kayitli": "Bu molekül PubChem'de kayıtlı:",
        "code":"kodu",
        "radar_warning":"Radar grafiği için en az 3 özellik (Örn: Tg, LOI, CTE) seçmelisiniz.",
        "takip_disi":"Takip Dışı",
        "water": "Su",
        "metanol": "Metanol",
        "etanol": "Etanol",
        "THF": "Tetrahidrofuran (THF)",
        "diklorometan": "Diklorometan (DCM)",
        "aseton": "Aseton (Polar Aprotik)",
        "kloroform": "Klorofom",
        "etil asetat": "Etil Asetat",
        "toluen": "Toluen (Aromatik)",
        "dietil_eter": "Dietil Eter",
        "hekzan": "Hekzan",
        "solubility_explanation_1": "*Analiz, 'Benzer Benzeri Çözer' ilkesine göre Polimer ",
        "solubility_explanation_2":" ve Çözücü arasındaki Hansen Parametresi farkına dayanır.*",
        "no_solubility":"Bu polimer çok dirençli görünüyor (veya çok özel bir çözücü gerektiriyor).",
        "aromatic":"Yüksek Aromatiklik (Zor parçalanma)",
        "halogen":"adet Halojen atomu (Kalıcılık/Toksisite riski)",
        "ether":"Eter grubu (Hidrofilik özellik)",
        "amide":"Amid bağı (Biyo-bozunurluk potansiyeli)",
        "ester":"Ester bağı (Hidroliz olabilir)",
        "easy": "Kolay",
        "hard": "Zor",
        "survival_rate": "Canlılık Oranı %",
        "best_fitness": "En İyi Hata",
        "avg_fitness": "Ortalama (Valid)",
        "gen": "Nesil",
        "diversity_chart": "Popülasyon Çeşitliliği",
        "convergence_chart": "Yakınsama Analizi",
        "evolution_panel": "### 🧬 Evrimsel Süreç İzleme Paneli",
        "api_key_explanation": "AI yorumu almak için https://aistudio.google.com/app/apikey adresinden ücretsiz anahtar alabilirsiniz.",
        "target": "Hedef",
        # Genel Başlıklar
        "app_subtitle": "Yapay Zeka Destekli Polimer Tasarlayıcısı",
        "sidebar_target_selection": "Hedef Seçimi",
        "sidebar_included_props": "Dahil Edilecek Özellikler",
        "sidebar_target_values": "Hedef Değerler",
        "sidebar_generations": "Evrim Nesli Sayısı",
        "sidebar_strategy": "Algoritma Stratejisi",
        "manual_title": "Manuel Polimer Analizi",
        "manual_desc": "Genetik algoritmayı çalıştırmadan, kendi polimerinizin (SMILES) özelliklerini ve retrosentezini hızlıca görün.",
        "manual_input_label": "Polimer SMILES kodu (örn: *CC(c1ccccc1)*):",
        "manual_btn": "Analiz Et",
        "manual_invalid": "Geçersiz SMILES kodu. Lütfen kimyasal sözdizimini kontrol edin.",
        "random_seed": "Rastgelelik Tohumu (0 = rastgele)",
        "random_seed_help": "0 dışında bir değer verirseniz aynı ayarlarla çalıştırma her seferinde aynı sonucu üretir (tekrarlanabilirlik).",
        "reliability_legend": "Model güvenilirliği: 🟢 yüksek · 🟡 orta · 🟠 sadece sıralama · 🔴 güvenilmez (doğrulama sonuçlarına göre)",
        "reliability_high": "Yüksek güvenilirlik — model bu özelliği veri setinde iyi tahmin ediyor.",
        "reliability_medium": "Orta güvenilirlik — kabaca doğru, mutlak değer ±belirsizlik içerir.",
        "reliability_low": "Düşük güvenilirlik — yalnızca sıralama için kullanın, mutlak değere güvenmeyin.",
        "reliability_unreliable": "Güvenilmez — bu model doğrulamada başarısız oldu (veri/etiket sorunu). Sonuca güvenmeyin.",
        "warn_unreliable": "Bu özellik(ler)in modeli güvenilmez, hedef olarak seçmek yanıltıcı olabilir:",
        "opt_mode": "Optimizasyon Yöntemi",
        "opt_mode_help": "NSGA-II: Çok amaçlı Pareto optimizasyonu; birden fazla hedef arasındaki ödünleşimleri (trade-off) korur. Ağırlıklı: Tüm hataları tek bir skorda birleştiren klasik yöntem.",
        "opt_nsga2": "NSGA-II (Pareto / Çok Amaçlı)",
        "opt_weighted": "Ağırlıklı (Tek Amaçlı)",
        "pareto_front": "Pareto Cephesi (Ödünleşim Çözümleri)",
        "pareto_desc": "Her satır, hedefler arasında farklı bir ödünleşim sunan, birbirine baskın olmayan bir polimer adayıdır.",
        "knee_note": "**⭐ Diz Noktası (Knee):** Tüm hedefleri en dengeli şekilde karşılayan çözüm. Üstte gösterilen sonuç budur.  🎯 = en düşük toplam hata (tek bir özellikte iyi ama dengesiz olabilir).",
        "knee_point": "Diz Noktası (En Dengeli)",
        "col_pick": "Seçim",
        "use_heuristic": "Sezgisel Başlangıç (Hedefe Yönelik)",
        "use_heuristic_help": "Açık: Popülasyon, hedefe uygun temel polimerlerle başlatılır (örn. düşük Tg için esnek omurgalar) ve mutasyonlar hedefe yönlendirilir. Kapalı: Klasik 'kör' başlangıç (yalnızca veri setinden rastgele).",
        "preserve_structure": "Önemli Yapıları Koru",
        "preserve_structure_help": "Açık: Mutasyonlar mevcut halkaları, aromatik sistemleri ve fonksiyonel grupları (ester, amid, imid, sülfon vb.) asla bozamaz; yalnızca ekleyebilir.",
        "sidebar_llm_settings": "LLM ChatBot Ayarları",
        "sidebar_btn_search": "Hedefi Ara",
        
        # Uyarılar ve Mesajlar
        "warn_no_target": "Lütfen optimize edilecek en az bir hedef seçin.",
        "warn_empty_pop": "Başlangıç popülasyonu boş veya geçersiz.",
        "msg_optimizing": "Genetik Algoritma Çalışıyor... Hedefler:",
        "msg_success": "✅ Optimizasyon Başarıyla Tamamlandı!",
        "msg_ai_thinking": "Yapay zeka düşünüyor...",
        
        # Özellikler (Properties)
        "prop_tg": "Tg (Camsı Geçiş Sıcaklığı)",
        "prop_td": "Td (Bozunma Sıcaklığı)",
        "prop_eps": "EPS (Dielektrik Sabiti)",
        "prop_tm": "Tm (Erime Sıcaklığı)",
        "prop_bandgap_bulk": "Bandgap Bulk (Elektriksel Band Aralığı - Bulk)",
        "prop_bandgap_chain": "Bandgap Chain (Elektriksel Band Aralığı - Zincir)",
        "prop_bandgap_crystal": "Bandgap Crystal (Elektriksel Band Aralığı - Kristal)",

        "prop_gas_perma": "Gas Permeability (Gaz Geçirgenliği)",
        "prop_refractive": "Refractive Index (Kırılma İndeksi)",
        "prop_loi": "LOI (Yanıcılık İndeksi)",
        "prop_solubility": "Çözünürlük (Hildebrand)",
        "prop_thermal_cond": "Isıl İletkenlik (Thermal Cond.)",
        "prop_cte": "Isıl Genleşme (CTE)",
        "prop_recyclability": "Kimyasal Geri Dönüşüm (Entalpi - ΔH_rop)",
        "prop_degradability": "Bozunabilirlik Skoru",
        "prop_hansen": "Hansen Çözünürlük Parametresi",
        
        # Sekmeler
        "tab_general": "Genel",
        "tab_structural": "Yapısal Analiz",
        "tab_evolution": "Evrim Geçmişi",
        "tab_report": "Raporlama",
        "tab_chatbot": "ChatBot",
        "tab_retro": "Retrosentez",
        
        # Metrikler ve Analizler
        "metric_total_error": "Toplam Hata:",
        "metric_sa_score": "Sentez Zorluğu (SA)",
        "metric_green_score": "Yeşil Skor",
        "env_analysis": "Çevresel Analiz:",
        "solubility_analysis": "Tahmini Çözünürlük Analizi",
        "soluble_in": "Çözünmesi Beklenenler:",
        "swelling_in": "Şişme / Zor Çözünme Beklenenler:",
        "radar_title": "Hedef Uyumluluk Analizi",
        
        # Sekme 2 & 3 (Yapı ve Evrim)
        "2d_structure": "2D Yapı (Teknik Çizim)",
        "3d_structure": "3D Konformasyon",
        "novelty_search": "Özgünlük Analizi (Novelty Search)",
        "similarity_to_train": "Eğitim Setine Benzerlik",
        "convergence_chart": "Yakınsama Analizi (Convergence)",
        "diversity_chart": "Popülasyon Çeşitliliği (Diversity)",
        
        # Raporlama
        "report_header": "Raporlama",
        "report_desc": "Proje verilerini CSV veya detaylı PDF raporu olarak dışa aktarabilirsiniz.",
        "btn_download_csv": "Veri Setini İndir (.csv)",
        "btn_create_pdf": "PDF Raporu Oluştur",
        
        # Retrosentez
        "retro_structural": "1. Yapısal Ayrıştırma",
        "retro_t5_pred": "2. T5-Model Tahmini",
        "btn_predict_monomer": "Monomerleri Tahmin Et",
        "proposed_monomers": "Önerilen Monomerler:"
    },
    "EN": {
        "Kompleks Kondenzasyon Polimeri": "Complex Condensation Polymer",
        "Özel Sentez (AI Analizi Önerilir)": "Special Synthesis (AI Analysis Recommended)",
        "Fonksiyonel Grup A": "Functional Group A",
        "Fonksiyonel Grup B": "Functional Group B",
        "Uç grupların reaksiyonu": "Reaction of End Groups",
        "Vinil Polimerizasyonu (Katılma)": "Vinyl Polymerization (Addition)",
        "Radikalik": "Radical",
        "Çift bağ açılması": "Double Bond Opening",
        "Asit + Amin -> Amid + Su": "Acid + Amine -> Amide + Water",
        "Polyester Sentezi": "Polyester Synthesis",
        "Kademeli Polimerizasyon": "Step-Growth Polymerization",
        "Dikarboksilik Asit": "Dicarboxylic Acid",
        "Diol": "Diol",
        "Asit + Alkol -> Ester + Su": "Acid + Alcohol -> Ester + Water",
        "Poliamid (Nylon) Sentezi": "Polyamide (Nylon) Synthesis",
        "Polikondenzasyon": "Polycondensation",
        "İzosiyanat + Alkol -> Üretan Bağı": "Isocyanate + Alcohol -> Urethane Linkage",
        "Diizosiyanat (Örn: TDI, MDI)": "Diisocyanate (e.g., TDI, MDI)",
        "Diol / Polyol": "Diol / Polyol",
        "Poliladisyon": "Polyaddition",
        "Poliüretan (PU) Sentezi": "Polyurethane (PU) Synthesis",
        "İzosiyanat + Amin -> Üre Bağı (Yan ürün yok)": "Isocyanate + Amine -> Urea Linkage (No Byproduct)",
        "Diamin (Diamine)": "Diamine",
        "Diizosiyanat (Diisocyanate)": "Diisocyanate",
        "Basamaklı Polimerizasyon (Hızlı)": "Step-Growth Polymerization (Fast)",
        "Poliüre (Polyurea) Sentezi": "Polyurea Synthesis",
        "Dianhidrit + Diamin -> Poliimid": "Dianhydride + Diamine -> Polyimide",
        "Dianhidrit": "Dianhydride",
        "Diamin": "Diamine",
        "Siklo-dehidrasyon": "Cyclo-dehydration",
        "Poliimid Sentezi": "Polyimide Synthesis",
        "Generation": "Generation",
        "Çeşitlilik" : "Diversity",
        "Uretilen Polimer": "Produced Polymer",
        "Hedeflenen": "Targeted",
        "yeşil_score": "Green Score",
        "predicted_monomers_image_caption": "Model's Proposed Building Blocks",
        "msg_predicting": "Predicting Monomers",
        "msg_success":"Monomer Prediction Successful!",
        "retro_structural": "1. Structural Decomposition",
        "retro_t5_pred": "2. T5-Model Prediction",
        "btn_predict_monomer": "Predict Monomers",
        "retro_t5_desc": "Our trained model analyzes the molecular structure to predict the monomers.",
        "retro_auto_failed": "Automatic analysis failed. Please review the proposed monomers manually.",
        "kayitli_degil": "No commercial record",
        "control": "Check",
        "commercial_check": "#### Commercial Availability Check (PubChem)",
        "baslangic_monomerleri":"**Possible Starting Monomers:**",
        "yontem": "Method",
        "mechanism": "Mechanism",
        "retro_analysis_header": "Retrosynthesis Analysis",
        "retro_auto_failed": "Automatic analysis failed. Please review the proposed monomers manually.",
        "retro_rule_method": "Real monomer structures from rule-based backbone disconnection (does not rely on the T5 model).",
        "retro_tentative": "A disconnection was found but it failed the verification test (functional-group / atom-conservation) — the monomers may be approximate or incomplete.",
        "retro_named_only": "This polymer has no recognisable polymerisation linkage; showing a likely mechanism only — explicit monomer structures could not be derived.",
        "get_free_api": "Get Free API Key (https://aistudio.google.com/app/apikey)",
        "chatbot_no_api": "To get detailed chemical insights about this polymer, please enter a **Google Gemini API Key** in the left menu.",
        "chatbot_desc": "Use the AI-powered ChatBot to get detailed chemical insights about the polymer structure and predicted properties.",
        "download":"Download",
        "report_ready": "Report is ready!",
        "report_getting_ready": "Report is being compiled... Please wait.",
        "pdf_report_info": "This report includes all predictions, molecular structure, AI insights, and any proposed synthesis plans.",
        "pdf_report": "PDF Report",
        "how_to_read": """                **How to Read These Charts?**
                * **Convergence (Top):** The green line should steadily decrease and eventually plateau. If the blue line closely follows the green, it indicates the population is "learning".
                * **Diversity (Bottom):** The red line should not drop to zero too quickly. If it does, the model has fallen into a "Premature Convergence" trap, meaning it has settled on a solution without adequately exploring the search space.""",
        "genetic_algorithm_report": "Genetic Algorithm Performance Report",
        "novelty_explanation": "*Similarity is calculated using the Tanimoto Index (Morgan Fingerprints).*",
        "closest_sim": "Closest Similarity",
        "novel":"**DISCOVERY:** This structure is NOT in the training set! A completely novel design.",
        "benzer_yapi": "View Similar Structure",
        "turev": "**Derivative:** Very similar to a structure in the training set.",
        "benzer":"Similar Record:",
        "copy":"**Copy:** The AI has memorized a data point from the training set.",
        "kayitli": "This molecule is registered in PubChem:",
        "code":"code",
        "radar_warning":"Radar chart requires at least 3 properties (e.g., Tg, LOI, CTE).",
        "takip_disi":"Out of Target",
        "water": "Water",
        "metanol": "Methanol",
        "etanol": "Ethanol",     
        "THF": "Tetrahydrofuran (THF)",
        "diklorometan": "Dichloromethane (DCM)",
        "aseton": "Acetone (Polar Aprotic)",
        "kloroform": "Chloroform",
        "etil asetat": "Ethyl Acetate",
        "toluen": "Toluene (Aromatic)",
        "dietil_eter": "Diethyl Ether",
        "hekzan": "Hexane",
        "solubility_explanation_1": "*The analysis is based on the Hansen Parameter difference between the Polymer ",
        "solubility_explanation_2": " and Solvent, following the 'Like Dissolves Like' principle.*",
        "no_solubility":"This polymer looks very resistant (or requires a very specific solvent).",
        "aromatic":"High Aromaticity (Difficult to Degrade)",
        "halogen":"Number of Halogen atoms (Persistence/Toxicity risk)",
        "ether":"Ether group (Hydrophilic character)",
        "amide":"Amide bond (Biodegradability potential)",
        "ester":"Ester bond (Hydrolyzable)",
        "easy": "Easy",
        "hard": "Hard",
        "best_fitness": "Best Fitness",
        "avg_fitness": "Average (Valid)",
        "survival_rate": "Survival Rate %",
        "gen": "Generation",
        "diversity_chart": "Population Diversity",
        "convergence_chart": "Convergence Analysis",
        "evolution_panel": "### 🧬 Evolutionary Process Tracking Panel",
        "api_key_explanation": "You can get a free key from https://aistudio.google.com/app/apikey to get AI feedback.",
        "target": "Target",
        # General Titles
        "app_subtitle": "AI-Powered Polymer Designer",
        "sidebar_target_selection": "Target Selection",
        "sidebar_included_props": "Properties to Include",
        "sidebar_target_values": "Target Values",
        "sidebar_generations": "Number of Generations",
        "sidebar_strategy": "Algorithm Strategy",
        "manual_title": "Manual Polymer Analysis",
        "manual_desc": "Quickly get the predicted properties and retrosynthesis for your own polymer (SMILES) without running the genetic algorithm.",
        "manual_input_label": "Polymer SMILES (e.g. *CC(c1ccccc1)*):",
        "manual_btn": "Analyze",
        "manual_invalid": "Invalid SMILES. Please check the chemical syntax.",
        "random_seed": "Random seed (0 = random)",
        "random_seed_help": "A non-zero value makes a run with the same settings reproduce the same result every time (reproducibility).",
        "reliability_legend": "Model reliability: 🟢 high · 🟡 medium · 🟠 ranking only · 🔴 unreliable (from validation on the dataset)",
        "reliability_high": "High reliability — the model predicts this property well on the dataset.",
        "reliability_medium": "Medium reliability — roughly right, with meaningful uncertainty on the absolute value.",
        "reliability_low": "Low reliability — use for ranking only; don't trust the absolute value.",
        "reliability_unreliable": "Unreliable — this model failed validation (data/label problem). Do not trust the result.",
        "warn_unreliable": "The model for these properties is unreliable; targeting them may be misleading:",
        "opt_mode": "Optimization Mode",
        "opt_mode_help": "NSGA-II: multi-objective Pareto optimization; keeps the trade-offs between competing targets. Weighted: the classic single-score method that collapses every error into one number.",
        "opt_nsga2": "NSGA-II (Pareto / Multi-objective)",
        "opt_weighted": "Weighted (Single-objective)",
        "pareto_front": "Pareto Front (Trade-off Solutions)",
        "pareto_desc": "Each row is a non-dominated polymer candidate offering a different trade-off between the targets.",
        "knee_note": "**⭐ Knee point:** the solution that balances all targets best — this is the result shown above.  🎯 = lowest total error (may be strong on one property but lopsided).",
        "knee_point": "Knee point (most balanced)",
        "col_pick": "Pick",
        "use_heuristic": "Heuristic Start (Goal-guided)",
        "use_heuristic_help": "On: the population is seeded with base polymers that match the goal (e.g. flexible backbones for low Tg) and mutations are steered toward the target. Off: the classic 'blind' start (random from the dataset only).",
        "preserve_structure": "Preserve Key Structures",
        "preserve_structure_help": "On: mutations can never destroy existing rings, aromatic systems or functional groups (ester, amide, imide, sulfone, ...); they may only add to them.",
        "sidebar_llm_settings": "LLM ChatBot Settings",
        "sidebar_btn_search": "Search Target",
        
        # Warnings and Messages
        "warn_no_target": "Please select at least one target to optimize.",
        "warn_empty_pop": "Initial population is empty or invalid.",
        "msg_optimizing": "Genetic Algorithm Running... Targets:",
        "msg_success": "✅ Optimization Completed Successfully!",
        "msg_ai_thinking": "AI is thinking...",
        
        # Properties
        "prop_tg": "Tg (Glass Transition Temp.)",
        "prop_td": "Td (Decomposition Temp.)",
        "prop_eps": "EPS (Dielectric Constant)",
        "prop_tm": "Tm (Melting Temp.)",
        "prop_bandgap_bulk": "Bandgap Bulk",
        "prop_bandgap_chain": "Bandgap Chain",
        "prop_bandgap_crystal": "Bandgap Crystal",
        "prop_gas_perma": "Gas Permeability",
        "prop_refractive": "Refractive Index",
        "prop_loi": "LOI (Limiting Oxygen Index)",
        "prop_solubility": "Solubility (Hildebrand)",
        "prop_thermal_cond": "Thermal Conductivity",
        "prop_cte": "Coefficient of Thermal Expansion (CTE)",
        "prop_recyclability": "Chemical Recyclability (ΔH_rop)",
        "prop_degradability": "Degradability Score",
        "prop_hansen": "Hansen Solubility Parameter",
        
        # Tabs
        "tab_general": "Overview",
        "tab_structural": "Structural Analysis",
        "tab_evolution": "Evolution History",
        "tab_report": "Reporting",
        "tab_chatbot": "ChatBot",
        "tab_retro": "Retrosynthesis",
        
        # Metrics & Analysis
        "metric_total_error": "Total Error:",
        "metric_sa_score": "Synthetic Accessibility (SA)",
        "metric_green_score": "Green Score",
        "env_analysis": "Environmental Analysis:",
        "solubility_analysis": "Estimated Solubility Analysis",
        "soluble_in": "Expected to Dissolve In:",
        "swelling_in": "Expected to Swell / Hardly Dissolve In:",
        "radar_title": "Target Compatibility Analysis",
        
        # Tabs 2 & 3
        "2d_structure": "2D Structure (Technical Drawing)",
        "3d_structure": "3D Structure (Conformation)",
        "novelty_search": "Novelty Search",
        "similarity_to_train": "Similarity to Training Set",
        "convergence_chart": "Convergence Analysis",
        "diversity_chart": "Population Diversity",
        
        # Reporting
        "report_header": "Reporting",
        "report_desc": "You can export project data as a CSV or a detailed PDF report.",
        "btn_download_csv": "Download Dataset (.csv)",
        "btn_create_pdf": "Generate PDF Report",
        
        # Retrosynthesis
        "retro_structural": "1. Structural Decomposition",
        "retro_t5_pred": "2. T5-Model Prediction",
        "btn_predict_monomer": "Predict Monomers",
        "proposed_monomers": "Proposed Monomers:"
    }
}
