LANGUAGES = {
    "TR": {
        
        "predicted_monomers_image_caption": "Modelin Önerdiği Yapı Taşları",
        "msg_predicting": "Monomerler Tahmin Ediliyor",
        "msg_success":"Monomer Tahmini Başarılı!",
        "retro_structural": "1. Yapısal Ayrıştırma",
        "retro_t5_pred": "2. T5-Model Tahmini",
        "btn_predict_monomer": "Monomerleri Tahmin Et",
        "retro_t5_desc": "Eğittiğimiz model, moleküler yapıyı analiz ederek monomerleri tahmin ediyor.",
        "retro_auto_failed": "Otomatik analiz yapılamadı. Lütfen önerilen monomerleri manuel olarak inceleyin.",
        "kayitli_degil": "Ticari kayit yok",
        "control": "Kontrol",
        "commercial_check": "#### Ticari Bulunabilirlik (PubChem)",
        "baslangic_monomerleri":"**Olası Başlangıç Monomerleri:**",
        "yontem": "Yöntem",
        "mechanism": "Mekanizma",
        "retro_analysis_header": "Retrosentez Analizi",
        "retro_auto_failed": "Otomatik analiz yapılamadı. Lütfen önerilen monomerleri manuel olarak inceleyin.",
        
        "get_free_api": "Ücretsiz API Key Almak İçin Tıkla(https://aistudio.google.com/app/apikey)",
        "chatbot_no_api": "Bu polimer hakkında detaylı kimyasal yorum almak için sol menüden **Google Gemini API Key** girmelisiniz.",
        "chatbot_desc": "PPolimer yapısı ve tahmin edilen özellikler hakkında detaylı kimyasal yorum almak için AI destekli ChatBot'u kullanın.",
        "download":"İndir",
        "report_ready": "Rapor hazır!",
        "report_getting_ready": "Rapor derleniyor... Lütfen bekleyin.",
        "pdf_report_info": "Bu rapor; tüm tahminleri, molekül yapısını, AI yorumlarını ve varsa sentez planını içerir.",
        "pdf_report": "PDF Raporu",
        "how_to_read": """                **Bu Grafikler Nasıl Okunur?**
                * **Yakınsama (Üst):** Yeşil çizgi sürekli düşmeli ve bir noktada yataylaşmalıdır (Plateau). Mavi çizgi yeşile çok yaklaşırsa popülasyon "öğrenmiş" demektir.
                * **Çeşitlilik (Alt):** Kırmızı çizginin sıfıra çok hızlı düşmemesi gerekir. Sıfıra düşerse model "Erken Yakınsama (Premature Convergence)" tuzağına düşmüştür; yani arama uzayını yeterince taramadan bir sonuca saplanmıştır.""",
        "genetic_algorithm_report": "Genetik Algoritma Performans Raporu",
        "novelty_explanation": "*Benzerlik, Tanimoto İndeksi (Morgan Fingerprints) kullanılarak hesaplanmıştır.*",
        "closest_sim": "En yakın benzerlik",
        "novel":"**KEŞİF:** Bu yapı eğitim setinde YOK! Tamamen özgün bir tasarım.",
        "benzer_yapi": "Benzer Yapıyı Gör",
        "turev": "**Türev:** Eğitim setindeki bir yapıya çok benziyor.",
        "benzer":"Benzer Kayıt:",
        "copy":"**Kopya:** Yapay zeka eğitim setindeki bir veriyi ezberlemiş.",
        "kayitli": "Bu molekül PubChem'de kayıtlı:",
        "code":"kodu",
        "radar_warning":"Radar grafiği için en az 3 özellik (Örn: Tg, LOI, CTE) seçmelisiniz.",
        "takip_disi":"Takip Dışı",
        "water": "Su",
        "metanol": "Metanol",
        "THF": "Tetrahidrofuran (THF)",
        "diklorometan": "Diklorometan (DCM)",
        "aseton": "Aseton (Polar Aprotik)",
        "kloroform": "Klorofom",
        "etil asetat": "Etil Asetat",
        "toluen": "Toluen (Aromatik)",
        "dietil_eter": "Dietil Eter",
        "hekzan": "Hekzan",
        "solubility_explanation_1": "*Analiz, 'Benzer Benzeri Çözer' ilkesine göre Polimer ",
        "solubility_explanation_2":" ve Çözücü arasındaki Hansen Parametresi farkına dayanır.*",
        "no_solubility":"Bu polimer çok dirençli görünüyor (veya çok özel bir çözücü gerektiriyor).",
        "aromatic":"Yüksek Aromatiklik (Zor parçalanma)",
        "halogen":"adet Halojen atomu (Kalıcılık/Toksisite riski)",
        "ether":"Eter grubu (Hidrofilik özellik)",
        "amide":"Amid bağı (Biyo-bozunurluk potansiyeli)",
        "ester":"Ester bağı (Hidroliz olabilir)",
        "easy": "Kolay",
        "hard": "Zor",
        "survival_rate": "Canlılık Oranı %",
        "best_fitness": "En İyi Hata",
        "avg_fitness": "Ortalama (Valid)",
        "gen": "Nesil",
        "diversity_chart": "Popülasyon Çeşitliliği",
        "convergence_chart": "Yakınsama Analizi",
        "evolution_panel": "### 🧬 Evrimsel Süreç İzleme Paneli",
        "api_key_explanation": "AI yorumu almak için https://aistudio.google.com/app/apikey adresinden ücretsiz anahtar alabilirsiniz.",
        "target": "Hedef",
        # Genel Başlıklar
        "app_subtitle": "Yapay Zeka Destekli Polimer Tasarlayıcısı",
        "sidebar_target_selection": "Hedef Seçimi",
        "sidebar_included_props": "Dahil Edilecek Özellikler",
        "sidebar_target_values": "Hedef Değerler",
        "sidebar_generations": "Evrim Nesli Sayısı",
        "sidebar_llm_settings": "LLM ChatBot Ayarları",
        "sidebar_btn_search": "Hedefi Ara",
        
        # Uyarılar ve Mesajlar
        "warn_no_target": "Lütfen optimize edilecek en az bir hedef seçin.",
        "warn_empty_pop": "Başlangıç popülasyonu boş veya geçersiz.",
        "msg_optimizing": "Genetik Algoritma Çalışıyor... Hedefler:",
        "msg_success": "✅ Optimizasyon Başarıyla Tamamlandı!",
        "msg_ai_thinking": "Yapay zeka düşünüyor...",
        
        # Özellikler (Properties)
        "prop_tg": "Tg (Camsı Geçiş Sıcaklığı)",
        "prop_td": "Td (Bozunma Sıcaklığı)",
        "prop_eps": "EPS (Dielektrik Sabiti)",
        "prop_tm": "Tm (Erime Sıcaklığı)",
        "prop_bandgap_bulk": "Bandgap Bulk (Elektriksel Band Aralığı - Bulk)",
        "prop_bandgap_chain": "Bandgap Chain (Elektriksel Band Aralığı - Zincir)",
        "prop_bandgap_crystal": "Bandgap Crystal (Elektriksel Band Aralığı - Kristal)",

        "prop_gas_perma": "Gas Permeability (Gaz Geçirgenliği)",
        "prop_refractive": "Refractive Index (Kırılma İndeksi)",
        "prop_loi": "LOI (Yanıcılık İndeksi)",
        "prop_solubility": "Çözünürlük (Hildebrand)",
        "prop_thermal_cond": "Isıl İletkenlik (Thermal Cond.)",
        "prop_cte": "Isıl Genleşme (CTE)",
        "prop_recyclability": "Kimyasal Geri Dönüşüm (Entalpi - ΔH_rop)",
        "prop_degradability": "Bozunabilirlik Skoru",
        "prop_hansen": "Hansen Çözünürlük Parametresi",
        
        # Sekmeler
        "tab_general": "Genel",
        "tab_structural": "Yapısal Analiz",
        "tab_evolution": "Evrim Geçmişi",
        "tab_report": "Raporlama",
        "tab_chatbot": "ChatBot",
        "tab_retro": "Retrosentez",
        
        # Metrikler ve Analizler
        "metric_total_error": "Toplam Hata:",
        "metric_sa_score": "Sentez Zorluğu (SA)",
        "metric_green_score": "Yeşil Skor",
        "env_analysis": "Çevresel Analiz:",
        "solubility_analysis": "Tahmini Çözünürlük Analizi",
        "soluble_in": "Çözünmesi Beklenenler:",
        "swelling_in": "Şişme / Zor Çözünme Beklenenler:",
        "radar_title": "Hedef Uyumluluk Analizi",
        
        # Sekme 2 & 3 (Yapı ve Evrim)
        "2d_structure": "2D Yapı (Teknik Çizim)",
        "3d_structure": "3D Konformasyon",
        "novelty_search": "Özgünlük Analizi (Novelty Search)",
        "similarity_to_train": "Eğitim Setine Benzerlik",
        "convergence_chart": "Yakınsama Analizi (Convergence)",
        "diversity_chart": "Popülasyon Çeşitliliği (Diversity)",
        
        # Raporlama
        "report_header": "Raporlama",
        "report_desc": "Proje verilerini CSV veya detaylı PDF raporu olarak dışa aktarabilirsiniz.",
        "btn_download_csv": "Veri Setini İndir (.csv)",
        "btn_create_pdf": "PDF Raporu Oluştur",
        
        # Retrosentez
        "retro_structural": "1. Yapısal Ayrıştırma",
        "retro_t5_pred": "2. T5-Model Tahmini",
        "btn_predict_monomer": "Monomerleri Tahmin Et",
        "proposed_monomers": "Önerilen Monomerler:"
    },
    "EN": {
        "predicted_monomers_image_caption": "Model's Proposed Building Blocks",
        "msg_predicting": "Predicting Monomers",
        "msg_success":"Monomer Prediction Successful!",
        "retro_structural": "1. Structural Decomposition",
        "retro_t5_pred": "2. T5-Model Prediction",
        "btn_predict_monomer": "Predict Monomers",
        "retro_t5_desc": "Our trained model analyzes the molecular structure to predict the monomers.",
        "retro_auto_failed": "Automatic analysis failed. Please review the proposed monomers manually.",
        "kayitli_degil": "No commercial record",
        "control": "Check",
        "commercial_check": "#### Commercial Availability Check (PubChem)",
        "baslangic_monomerleri":"**Possible Starting Monomers:**",
        "yontem": "Method",
        "mechanism": "Mechanism",
        "retro_analysis_header": "Retrosynthesis Analysis",
        "retro_auto_failed": "Automatic analysis failed. Please review the proposed monomers manually.",
        "get_free_api": "Get Free API Key (https://aistudio.google.com/app/apikey)",
        "chatbot_no_api": "To get detailed chemical insights about this polymer, please enter a **Google Gemini API Key** in the left menu.",
        "chatbot_desc": "Use the AI-powered ChatBot to get detailed chemical insights about the polymer structure and predicted properties.",
        "download":"Download",
        "report_ready": "Report is ready!",
        "report_getting_ready": "Report is being compiled... Please wait.",
        "pdf_report_info": "This report includes all predictions, molecular structure, AI insights, and any proposed synthesis plans.",
        "pdf_report": "PDF Report",
        "how_to_read": """                **How to Read These Charts?**
                * **Convergence (Top):** The green line should steadily decrease and eventually plateau. If the blue line closely follows the green, it indicates the population is "learning".
                * **Diversity (Bottom):** The red line should not drop to zero too quickly. If it does, the model has fallen into a "Premature Convergence" trap, meaning it has settled on a solution without adequately exploring the search space.""",
        "genetic_algorithm_report": "Genetic Algorithm Performance Report",
        "novelty_explanation": "*Similarity is calculated using the Tanimoto Index (Morgan Fingerprints).*",
        "closest_sim": "Closest Similarity",
        "novel":"**DISCOVERY:** This structure is NOT in the training set! A completely novel design.",
        "benzer_yapi": "View Similar Structure",
        "turev": "**Derivative:** Very similar to a structure in the training set.",
        "benzer":"Similar Record:",
        "copy":"**Copy:** The AI has memorized a data point from the training set.",
        "kayitli": "This molecule is registered in PubChem:",
        "code":"code",
        "radar_warning":"Radar chart requires at least 3 properties (e.g., Tg, LOI, CTE).",
        "takip_disi":"Out of Target",
        "water": "Water",
        "metanol": "Methanol",
        "THF": "Tetrahydrofuran (THF)",
        "diklorometan": "Dichloromethane (DCM)",
        "aseton": "Acetone (Polar Aprotic)",
        "kloroform": "Chloroform",
        "etil asetat": "Ethyl Acetate",
        "toluen": "Toluene (Aromatic)",
        "dietil_eter": "Diethyl Ether",
        "hekzan": "Hexane",
        "solubility_explanation_1": "*The analysis is based on the Hansen Parameter difference between the Polymer ",
        "solubility_explanation_2": " and Solvent, following the 'Like Dissolves Like' principle.*",
        "no_solubility":"This polymer looks very resistant (or requires a very specific solvent).",
        "aromatic":"High Aromaticity (Difficult to Degrade)",
        "halogen":"Number of Halogen atoms (Persistence/Toxicity risk)",
        "ether":"Ether group (Hydrophilic character)",
        "amide":"Amide bond (Biodegradability potential)",
        "ester":"Ester bond (Hydrolyzable)",
        "easy": "Easy",
        "hard": "Hard",
        "best_fitness": "Best Fitness",
        "avg_fitness": "Average (Valid)",
        "survival_rate": "Survival Rate %",
        "gen": "Generation",
        "diversity_chart": "Population Diversity",
        "convergence_chart": "Convergence Analysis",
        "evolution_panel": "### 🧬 Evolutionary Process Tracking Panel",
        "api_key_explanation": "You can get a free key from https://aistudio.google.com/app/apikey to get AI feedback.",
        "target": "Target",
        # General Titles
        "app_subtitle": "AI-Powered Polymer Designer",
        "sidebar_target_selection": "Target Selection",
        "sidebar_included_props": "Properties to Include",
        "sidebar_target_values": "Target Values",
        "sidebar_generations": "Number of Generations",
        "sidebar_llm_settings": "LLM ChatBot Settings",
        "sidebar_btn_search": "Search Target",
        
        # Warnings and Messages
        "warn_no_target": "Please select at least one target to optimize.",
        "warn_empty_pop": "Initial population is empty or invalid.",
        "msg_optimizing": "Genetic Algorithm Running... Targets:",
        "msg_success": "✅ Optimization Completed Successfully!",
        "msg_ai_thinking": "AI is thinking...",
        
        # Properties
        "prop_tg": "Tg (Glass Transition Temp.)",
        "prop_td": "Td (Decomposition Temp.)",
        "prop_eps": "EPS (Dielectric Constant)",
        "prop_tm": "Tm (Melting Temp.)",
        "prop_bandgap_bulk": "Bandgap Bulk",
        "prop_bandgap_chain": "Bandgap Chain",
        "prop_bandgap_crystal": "Bandgap Crystal",
        "prop_gas_perma": "Gas Permeability",
        "prop_refractive": "Refractive Index",
        "prop_loi": "LOI (Limiting Oxygen Index)",
        "prop_solubility": "Solubility (Hildebrand)",
        "prop_thermal_cond": "Thermal Conductivity",
        "prop_cte": "Coefficient of Thermal Expansion (CTE)",
        "prop_recyclability": "Chemical Recyclability (ΔH_rop)",
        "prop_degradability": "Degradability Score",
        "prop_hansen": "Hansen Solubility Parameter",
        
        # Tabs
        "tab_general": "General",
        "tab_structural": "Structural Analysis",
        "tab_evolution": "Evolution History",
        "tab_report": "Reporting",
        "tab_chatbot": "ChatBot",
        "tab_retro": "Retrosynthesis",
        
        # Metrics & Analysis
        "metric_total_error": "Total Error:",
        "metric_sa_score": "Synthetic Accessibility (SA)",
        "metric_green_score": "Green Score",
        "env_analysis": "Environmental Analysis:",
        "solubility_analysis": "Estimated Solubility Analysis",
        "soluble_in": "Expected to Dissolve In:",
        "swelling_in": "Expected to Swell / Hardly Dissolve In:",
        "radar_title": "Target Compatibility Analysis",
        
        # Tabs 2 & 3
        "2d_structure": "2D Structure (Technical Drawing)",
        "3d_structure": "3D Conformation",
        "novelty_search": "Novelty Search",
        "similarity_to_train": "Similarity to Training Set",
        "convergence_chart": "Convergence Analysis",
        "diversity_chart": "Population Diversity",
        
        # Reporting
        "report_header": "Reporting",
        "report_desc": "You can export project data as a CSV or a detailed PDF report.",
        "btn_download_csv": "Download Dataset (.csv)",
        "btn_create_pdf": "Generate PDF Report",
        
        # Retrosynthesis
        "retro_structural": "1. Structural Decomposition",
        "retro_t5_pred": "2. T5-Model Prediction",
        "btn_predict_monomer": "Predict Monomers",
        "proposed_monomers": "Proposed Monomers:"
    }
}
